replicaCount: 1

image:
  repository: devops-assignment-app
  tag: local
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  nodePort: 30080

env:
  port: 3000
  readyDelayMs: 5000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 2
    periodSeconds: 2
    timeoutSeconds: 2
    failureThreshold: 5

podAnnotations: {}

monitoring:
  enabled: true

  prometheus:
    image:
      repository: prom/prometheus
      tag: v2.54.1
    service:
      nodePort: 30090
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi

  grafana:
    image:
      repository: grafana/grafana
      tag: "11.1.4"
    service:
      nodePort: 30030
    adminUser: admin
    adminPassword: admin
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
