{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-grafana-admin
  labels:
    {{- include "app.componentLabels" (dict "ctx" . "component" "grafana") | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.monitoring.grafana.adminUser | quote }}
  admin-password: {{ .Values.monitoring.grafana.adminPassword | quote }}
{{- end }}
